### PR TITLE
Added/Updated icons, Switched to svg

### PR DESCRIPTION
**Pull request by laurenmancke**
Added Medium, Periscope, Phone, Snapchat, Vine, and Xing icons
Updated Instagram and Google+ icons
Switched to svg, rather than icon font

### CODE REVIEW

**Comment by nickcernis** [comment]
This looks great. I tested in IE (9 / 10 / 11), Firefox, Chrome, Safari, Android 4.4+, and iOS without issue. Thanks for your work, @laurenmancke!

### Notes
1. Should the version be bumped to 2.0 instead of 1.1 because it contains a breaking change? (Removal of `simple_social_default_glyphs` filter.)
2. Should we mention removal of that filter in the readme and warn users in advance?

    > “When you deprecate part of your public API, you should do two things: (1) update your documentation to let users know about the change, (2) issue a new minor release with the deprecation in place. Before you completely remove the functionality in a new major release there should be at least one minor release that contains the deprecation so that users can smoothly transition to the new API.”
    > – http://semver.org/#how-should-i-handle-deprecating-functionality

    If we're not going to do a minor release or blog post before removing the filter, I suggest at least adding an [upgrade notice](https://www.smashingmagazine.com/2011/11/improve-wordpress-plugins-readme-txt/#upgrade-notice) to the readme to increase the chance of people seeing it before upgrading. Customers have changed or reordered icons with that filter, and there are community themes that include it by default. This update may break ordering/custom icons for those users.

3. Should we let users know how to reorder icons in the [FAQ](https://github.com/copyblogger/simple-social-icons/pull/28/commits/9a6e92242643f2834f026eee2321967503e208b1#diff-04c6e90faac2675aa89e2176d2eec7d8R25)? I made [a gist for this](https://gist.github.com/nickcernis/1ad4e16c1323357cf18db401567555e2) if needed. 

4. Finally, just a reminder to bump the stylesheet version at https://github.com/copyblogger/simple-social-icons/pull/28/commits/9a6e92242643f2834f026eee2321967503e208b1#diff-12a1b54f83ab74a5deb89c7b9c8cc7eeR405 during release to bust those aggressive caches we see in support. :-)

cc @bgardner @nathanrice

**Comment by bgardner** [comment]
@nickcernis The big question ... is there a way we can keep the filter in based on he changes that @laurenmancke made?

**Comment by bgardner** [comment]
If not, then I'd suggest we move forward, with documentation in place to help folks re-order the new icons (per your gist) and maybe write a blog post as well documenting the change (and why.)

**Comment by nickcernis** [comment]
@bgardner I can't think of a clean way to leave the filter in. It would mean leaving the icon font as part of the plugin, then enqueuing it and falling back to the font version if the `simple_social_default_glyphs` filter was in use. It also means maintaining the icon font alongside the svg icons in the future.

I think we should do what you say and document/inform as best we can. Proposed plan:

1. Set the version to 2.0 instead of 1.1.
2. Add the following to the 2.0 changelog in the readme.txt:

    > Removed the `simple_social_default_glyphs` filter, as the plugin now uses vector icons in place of an icon font.

3. Add an upgrade notice to the readme with this text:

    > This version removes the `simple_social_default_glyphs` filter: [link to blog post].

4. Add a link in the readme.txt FAQ to a [reorder gist](https://gist.github.com/nickcernis/1ad4e16c1323357cf18db401567555e2) so it's clear how to reorder icons once the new vector version goes live.

5. Write a blog post explaining the change as an early warning, with this rough outline:
    - Detail the new icons and the general rationale behind moving away from icon fonts.
    - Link to a version developers can use to test changes, and invite beta testers to try it.
    - Explain the `simple_social_default_glyphs` filter won't be available in the new version.
    - Show an example of changing the order of the icons.
    - Show an example of changing one of the included icons.
    - Show an example of adding an additional custom icon if needed.
    - Invite developers to contact us if they need further help.

6. Give folks some time to edit their themes and plugins.

7. Bump versions in the plugin including the [cache-buster](https://github.com/copyblogger/simple-social-icons/pull/28/commits/9a6e92242643f2834f026eee2321967503e208b1#diff-12a1b54f83ab74a5deb89c7b9c8cc7eeR405), then release it.

That probably sounds like a heap of extra work, but I'm just trying to minimise any disruption caused by the change. If I can help with any of it (extra commits or the blog post), please let me know. cc @laurenmancke

**Comment by bgardner** [comment]
@nickcernis @dreamwhisper I'd like to move forward on getting this released. Is the filter issue the only one at this point that will affect users? In other words, if we follow the steps that Nick points out, would we be ok to set this train in motion?  I'd be happy to write the first draft of the blog post and then have either/both of you look it over from a support perspective.

**Comment by nickcernis** [comment]
@bgardner @dreamwhisper Dropping the filter was the only issue I can foresee at the moment. Happy to help however I can.

**Comment by nickcernis** [comment]
Also noting that Vine may be closed down:
http://www.theverge.com/2016/10/27/13437576/twitter-killing-vine

Although there are some hopes that it will be sold and live on: http://www.theverge.com/2016/11/7/13556764/twitter-selling-vine 

Probably best to leave the Vine icon in for now until it becomes more clear.

**Pull request merged**
